"""
Deterministic adaptive orchestrator for Phase 3.

The orchestrator coordinates specialized phishing detection
agents and dynamically determines whether additional evidence
should be collected.

The current policy is deterministic and rule-based.

This interface is intentionally designed so that the policy
can later be replaced by a reinforcement-learning policy
without changing the underlying agents.
"""

from __future__ import annotations

import time
from dataclasses import dataclass, field
from typing import Any

from phishing_detection.agents.base import AgentContext
from phishing_detection.agents.confidence import (
    assess_agent_result,
)
from phishing_detection.agents.email_agent import EmailAnalysisAgent
from phishing_detection.agents.result import AgentResult
from phishing_detection.agents.sender_agent import (
    SenderAnalysisAgent,
)
from phishing_detection.agents.url_agent import URLAnalysisAgent


@dataclass
class OrchestrationStep:
    """
    Record of one orchestration decision.

    Parameters
    ----------
    step_number:
        Sequential step number.

    agent_name:
        Agent considered or executed.

    action:
        Action taken by the orchestrator.

    reason:
        Explanation for the action.

    confidence:
        Confidence available at the time of the decision.

    uncertainty:
        Uncertainty available at the time of the decision.
    """

    step_number: int
    agent_name: str
    action: str
    reason: str
    confidence: float | None = None
    uncertainty: float | None = None

    def to_dict(self) -> dict[str, Any]:
        """Convert the step to a dictionary."""

        return {
            "step_number": self.step_number,
            "agent_name": self.agent_name,
            "action": self.action,
            "reason": self.reason,
            "confidence": self.confidence,
            "uncertainty": self.uncertainty,
        }


@dataclass
class OrchestrationResult:
    """
    Final output produced by the orchestrator.

    Parameters
    ----------
    label:
        Final binary prediction.

    label_name:
        Final human-readable prediction.

    phishing_probability:
        Aggregated phishing probability.

    confidence:
        Confidence in the final prediction.

    uncertainty:
        Uncertainty in the final prediction.

    agent_results:
        Results generated by each executed agent.

    decision_trace:
        Ordered record of orchestration decisions.

    evidence:
        Combined evidence from all executed agents.

    metadata:
        Additional orchestration metadata.
    """

    label: int
    label_name: str
    phishing_probability: float
    confidence: float
    uncertainty: float
    agent_results: list[AgentResult] = field(
        default_factory=list
    )
    decision_trace: list[OrchestrationStep] = field(
        default_factory=list
    )
    evidence: list[Any] = field(
        default_factory=list
    )
    metadata: dict[str, Any] = field(
        default_factory=dict
    )

    def __post_init__(self) -> None:
        self._validate()

    def _validate(self) -> None:
        """Validate the orchestration result."""

        if self.label not in {0, 1}:
            raise ValueError(
                "label must be 0 or 1."
            )

        expected_name = (
            "phishing"
            if self.label == 1
            else "legitimate"
        )

        if self.label_name != expected_name:
            raise ValueError(
                "label_name does not match label."
            )

        for field_name, value in (
            (
                "phishing_probability",
                self.phishing_probability,
            ),
            ("confidence", self.confidence),
            ("uncertainty", self.uncertainty),
        ):
            if not 0.0 <= float(value) <= 1.0:
                raise ValueError(
                    f"{field_name} must be between 0 and 1."
                )

    @property
    def is_phishing(self) -> bool:
        """Return True when the final decision is phishing."""

        return self.label == 1

    @property
    def is_legitimate(self) -> bool:
        """Return True when the final decision is legitimate."""

        return self.label == 0

    @property
    def agent_count(self) -> int:
        """Return the number of executed agents."""

        return len(self.agent_results)

    @property
    def evidence_count(self) -> int:
        """Return the number of collected evidence items."""

        return len(self.evidence)

    def to_dict(self) -> dict[str, Any]:
        """Return a serializable representation."""

        return {
            "label": self.label,
            "label_name": self.label_name,
            "phishing_probability": (
                self.phishing_probability
            ),
            "confidence": self.confidence,
            "uncertainty": self.uncertainty,
            "agent_results": [
                {
                    "agent_name": result.agent_name,
                    "modality": result.modality,
                    "label": result.label,
                    "label_name": result.label_name,
                    "phishing_probability": (
                        result.phishing_probability
                    ),
                    "confidence": result.confidence,
                    "uncertainty": result.uncertainty,
                }
                for result in self.agent_results
            ],
            "decision_trace": [
                step.to_dict()
                for step in self.decision_trace
            ],
            "evidence": [
                evidence.to_dict()
                for evidence in self.evidence
            ],
            "metadata": self.metadata,
        }


class OrchestratorAgent:
    """
    Coordinate specialized phishing detection agents.

    Parameters
    ----------
    email_agent:
        Specialized email analysis agent.

    url_agent:
        Specialized URL analysis agent.

    sender_agent:
        Specialized sender analysis agent.

    confidence_threshold:
        Confidence above which additional evidence is normally
        considered unnecessary.

    max_agents:
        Maximum number of agents that may be executed.
    """

    def __init__(
        self,
        email_agent: EmailAnalysisAgent,
        url_agent: URLAnalysisAgent,
        sender_agent: SenderAnalysisAgent,
        confidence_threshold: float = 0.90,
        max_agents: int = 3,
    ) -> None:
        if not 0.0 <= confidence_threshold <= 1.0:
            raise ValueError(
                "confidence_threshold must be between 0 and 1."
            )

        if max_agents < 1:
            raise ValueError(
                "max_agents must be at least 1."
            )

        self.email_agent = email_agent
        self.url_agent = url_agent
        self.sender_agent = sender_agent
        self.confidence_threshold = (
            confidence_threshold
        )
        self.max_agents = max_agents

    def _record_step(
        self,
        trace: list[OrchestrationStep],
        agent_name: str,
        action: str,
        reason: str,
        result: AgentResult | None = None,
    ) -> None:
        """Append an orchestration step."""

        confidence = None
        uncertainty = None

        if result is not None:
            assessment = assess_agent_result(
                result
            )

            confidence = assessment.confidence
            uncertainty = assessment.uncertainty

        trace.append(
            OrchestrationStep(
                step_number=len(trace) + 1,
                agent_name=agent_name,
                action=action,
                reason=reason,
                confidence=confidence,
                uncertainty=uncertainty,
            )
        )

    def _should_continue(
        self,
        result: AgentResult,
    ) -> bool:
        """
        Determine whether additional evidence should be collected.
        """

        assessment = assess_agent_result(result)

        return (
            assessment.confidence
            < self.confidence_threshold
        )

    @staticmethod
    def _aggregate_results(
        results: list[AgentResult],
    ) -> tuple[float, int]:
        """
        Aggregate agent probabilities.

        The current deterministic policy uses the arithmetic mean.

        This is intentionally simple and transparent. A future
        learned evidence-fusion policy can replace this function.
        """

        if not results:
            return 0.5, 0

        probability = sum(
            result.phishing_probability
            for result in results
        ) / len(results)

        probability = round(
            probability,
            10,
        )

        label = int(
            probability >= 0.5
        )

        return probability, label

    def _create_final_result(
        self,
        results: list[AgentResult],
        trace: list[OrchestrationStep],
        start_time: float,
    ) -> OrchestrationResult:
        """Create the final orchestration result."""

        probability, label = (
            self._aggregate_results(results)
        )

        label_name = (
            "phishing"
            if label == 1
            else "legitimate"
        )

        confidence = (
            probability
            if label == 1
            else 1.0 - probability
        )

        uncertainty = round(
            1.0 - confidence,
            10,
        )

        combined_evidence = []

        for result in results:
            combined_evidence.extend(
                result.evidence
            )

        total_time_ms = (
            time.perf_counter() - start_time
        ) * 1000.0

        return OrchestrationResult(
            label=label,
            label_name=label_name,
            phishing_probability=probability,
            confidence=confidence,
            uncertainty=uncertainty,
            agent_results=results,
            decision_trace=trace,
            evidence=combined_evidence,
            metadata={
                "policy": "deterministic_confidence_threshold",
                "confidence_threshold": (
                    self.confidence_threshold
                ),
                "agents_executed": len(results),
                "total_execution_time_ms": (
                    total_time_ms
                ),
            },
        )

    def analyze(
        self,
        context: AgentContext,
    ) -> OrchestrationResult:
        """
        Execute adaptive multi-agent analysis.

        The deterministic policy starts with the Email Agent,
        then gathers additional evidence when confidence is
        below the configured threshold.
        """

        start_time = time.perf_counter()

        results: list[AgentResult] = []

        trace: list[OrchestrationStep] = []

        # -----------------------------------------------------
        # STEP 1: EMAIL ANALYSIS
        # -----------------------------------------------------

        if self.email_agent.can_analyze(context):

            self._record_step(
                trace=trace,
                agent_name=(
                    self.email_agent.get_agent_name()
                ),
                action="execute",
                reason=(
                    "Email content is available and "
                    "email analysis is the primary "
                    "initial evidence source."
                ),
            )

            email_result = self.email_agent.analyze(
                context
            )

            results.append(email_result)

            if not self._should_continue(
                email_result
            ):
                self._record_step(
                    trace=trace,
                    agent_name=(
                        self.email_agent.get_agent_name()
                    ),
                    action="stop",
                    reason=(
                        "Email analysis confidence is above "
                        "the configured threshold."
                    ),
                    result=email_result,
                )

                return self._create_final_result(
                    results,
                    trace,
                    start_time,
                )

            self._record_step(
                trace=trace,
                agent_name=(
                    self.email_agent.get_agent_name()
                ),
                action="continue",
                reason=(
                    "Email analysis confidence is below "
                    "the configured threshold; additional "
                    "evidence is required."
                ),
                result=email_result,
            )

        else:
            self._record_step(
                trace=trace,
                agent_name=(
                    self.email_agent.get_agent_name()
                ),
                action="skip",
                reason=(
                    "Email content is unavailable."
                ),
            )

        # -----------------------------------------------------
        # STEP 2: URL ANALYSIS
        # -----------------------------------------------------

        if (
            len(results) < self.max_agents
            and self.url_agent.can_analyze(context)
        ):

            self._record_step(
                trace=trace,
                agent_name=(
                    self.url_agent.get_agent_name()
                ),
                action="execute",
                reason=(
                    "Additional evidence is required and "
                    "URL information is available."
                ),
            )

            url_result = self.url_agent.analyze(
                context
            )

            results.append(url_result)

            if not self._should_continue(
                url_result
            ):
                self._record_step(
                    trace=trace,
                    agent_name=(
                        self.url_agent.get_agent_name()
                    ),
                    action="stop",
                    reason=(
                        "URL analysis confidence is above "
                        "the configured threshold."
                    ),
                    result=url_result,
                )

                return self._create_final_result(
                    results,
                    trace,
                    start_time,
                )

            self._record_step(
                trace=trace,
                agent_name=(
                    self.url_agent.get_agent_name()
                ),
                action="continue",
                reason=(
                    "URL analysis remains uncertain; "
                    "sender evidence may provide additional "
                    "information."
                ),
                result=url_result,
            )

        else:
            self._record_step(
                trace=trace,
                agent_name=(
                    self.url_agent.get_agent_name()
                ),
                action="skip",
                reason=(
                    "URL analysis is unavailable or the "
                    "maximum agent budget has been reached."
                ),
            )

        # -----------------------------------------------------
        # STEP 3: SENDER ANALYSIS
        # -----------------------------------------------------

        if (
            len(results) < self.max_agents
            and self.sender_agent.can_analyze(context)
        ):

            self._record_step(
                trace=trace,
                agent_name=(
                    self.sender_agent.get_agent_name()
                ),
                action="execute",
                reason=(
                    "Additional evidence is required and "
                    "sender/header information is available."
                ),
            )

            sender_result = self.sender_agent.analyze(
                context
            )

            results.append(sender_result)

            self._record_step(
                trace=trace,
                agent_name=(
                    self.sender_agent.get_agent_name()
                ),
                action="stop",
                reason=(
                    "Sender analysis completed; the "
                    "maximum planned evidence-gathering "
                    "depth has been reached."
                ),
                result=sender_result,
            )

        else:
            self._record_step(
                trace=trace,
                agent_name=(
                    self.sender_agent.get_agent_name()
                ),
                action="skip",
                reason=(
                    "Sender analysis is unavailable or the "
                    "maximum agent budget has been reached."
                ),
            )

        return self._create_final_result(
            results,
            trace,
            start_time,
        )