"""
Tests for Phase 2 artifact validation.
"""

from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]

VALIDATOR = (
    PROJECT_ROOT
    / "scripts"
    / "validate_phase2_artifacts.py"
)


OUTPUT_DIR = (
    PROJECT_ROOT
    / "experiments"
    / "baselines"
    / "outputs"
)


def test_artifact_validator_exists():
    assert VALIDATOR.exists()


def test_artifact_validator_contains_required_model_checks():
    content = VALIDATOR.read_text(
        encoding="utf-8"
    )

    required_models = [
        "email_logistic_regression.pkl",
        "email_linear_svm.pkl",
        "email_random_forest.pkl",
        "url_logistic_regression.pkl",
        "url_random_forest.pkl",
        "url_gradient_boosting.pkl",
    ]

    for model in required_models:
        assert model in content


def test_artifact_validator_checks_configuration():
    content = VALIDATOR.read_text(
        encoding="utf-8"
    )

    assert "phase2_baseline.yaml" in content
    assert "random_state: 42" in content
    assert "email_linear_svm" in content
    assert "url_random_forest" in content


def test_artifact_validator_checks_comparison_table():
    content = VALIDATOR.read_text(
        encoding="utf-8"
    )

    assert "baseline_model_comparison.csv" in content
    assert "Validation F1" in content
    assert "Test F1" in content
    assert "Test ROC-AUC" in content
    assert "Test PR-AUC" in content


def test_artifact_validator_checks_error_analysis():
    content = VALIDATOR.read_text(
        encoding="utf-8"
    )

    assert "error_analysis_summary.csv" in content
    assert "False Positives" in content
    assert "False Negatives" in content


def test_validation_report_is_created_after_validation():
    validation_report = (
        OUTPUT_DIR
        / "phase2_artifact_validation.json"
    )

    # The file is generated by the validation script.
    # The test only verifies its structure when present.
    if not validation_report.exists():
        return

    assert validation_report.stat().st_size > 0